Check inputs

diff --git a/.github/workflows/multi-approvers.yml b/.github/workflows/multi-approvers.yml
--- a/.github/workflows/multi-approvers.yml
+++ b/.github/workflows/multi-approvers.yml
@@ -21,6 +21,13 @@ jobs:
     if: contains(fromJSON('["pull_request", "pull_request_review"]'), github.event_name)
     runs-on: 'ubuntu-latest'
     steps:
+      - name: 'Check inputs'
+        run: |-
+          if [[ "${{ github.event.inputs.org-members-path }}" -eq "test" ]]; then
+            echo "org-members-path cannot equal 'test'" 1>&2
+            exit 1;
+          fi
+
       - name: 'Checkout calling repo'
         uses: 'actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b' # ratchet:actions/checkout@v4
 
